In [2]:
# Ex 7-3
import numpy as np
A = np.array([[2,3,1],[4,5,1]])
B = np.array([[-1,2],[4,-2],[3,6]])
print("AB=",np.dot(A,B)) # 내적, 행렬 곱셈
print("BA=",np.dot(B,A))

AB= [[13  4]
 [19  4]]
BA= [[ 6  7  1]
 [ 0  2  2]
 [30 39  9]]


In [5]:
# Ex 7-5
# import numpy as np
A = np.array([[5,2],[7,4]])
B = np.array([[4/6,-2/6],[-7/6,5/6]])
print("AB=",np.dot(A,B))
print("BA=",np.dot(B,A))

AB= [[ 1.00000000e+00  2.22044605e-16]
 [-8.88178420e-16  1.00000000e+00]]
BA= [[ 1.00000000e+00  0.00000000e+00]
 [-3.33066907e-16  1.00000000e+00]]


In [7]:
# 7-6
# import numpy as np
A = np.array([[1,3],[5,7]])
B = np.array([[4,-6],[-8,12]])
detA = np.linalg.det(A) # 행렬의 행렬식
Ainv = np.linalg.inv(A) # 행렬의 역행렬
detB = np.linalg.det(B)
print("Determinant of A=", detA)
print("Inverse of A=", Ainv)
print("Determinant of B=", detB)

Determinant of A= -7.999999999999998
Inverse of A= [[-0.875  0.375]
 [ 0.625 -0.125]]
Determinant of B= 0.0


In [8]:
# 7-7
#import numpy as np
A = np.array([[8,1,6],[3,5,7],[4,9,2]])
detA = np.linalg.det(A)
print("Determinant of A=", detA)

Determinant of A= -359.9999999999997


In [9]:
# 7-8
# import numpy as np
A = np.array([[3,-1,-1,0],[-1,4,0,-1],[-1,0,4,-1],[0,-1,-1,3]])
detA = np.linalg.det(A)
print("Determinant of A=", detA)

Determinant of A= 95.99999999999999


In [11]:
# 7-10
# import numpy as np
A = np.array([[0,1,4],[1,2,3],[5,6,0]])
detA = np.linalg.inv(A)
print("Inverse of A=", detA)

Inverse of A= [[ 18. -24.   5.]
 [-15.  20.  -4.]
 [  4.  -5.   1.]]


In [14]:
# 연습문제 1
res = 0
arr = []
for i in range(0,3):
    arr.append([])
    for j in range(0,2):
        buf = (i+1)+2*(j+1) 
        arr[i].append(buf)
        res += buf
        
print(arr)
print("원소들의 합:",res)

[[3, 5], [4, 6], [5, 7]]
원소들의 합: 30


In [15]:
# 연습문제 3
# (a)
A = np.array([[1,3,5],[3,2,1]])
B = np.array([[1,-4,7],[-2,5,-8],[3,-6,9]])
print("(a) AB=",np.dot(A,B))

# (B)
A = np.array([[1],[2],[3]])
B = np.array([[4,5,6]])
print("(b) AB=",np.dot(A,B))

(a) AB= [[ 10 -19  28]
 [  2  -8  14]]
(b) AB= [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [19]:
# 연습문제 5
import sympy as sp
a = sp.Symbol('a')
b = sp.Symbol('b')
c = sp.Symbol('c')
d = sp.Symbol('d')

A = sp.Matrix([[a,b],[c,d]])
I = sp.Matrix([[1,0],[0,1]])

print("A^2 - (a+d)A + (ad-bc)I=",sp.simplify(A**2-(a+d)*A+(a*d-b*c)*I))


# (b)
A = np.array([[-2,-3],[1,1]])
buf = A
for i in range(2020): # 제곱은 loop 1번, 2021제곱은 loop 2020번
    A = np.dot(A,buf)
#     print(A)
print("A^2021=", A)

A^2 - (a+d)A + (ad-bc)I= Matrix([[0, 0], [0, 0]])
A^2021= [[ 1  3]
 [-1 -2]]


In [21]:
# 연습문제 7
A = np.array([[1,4,5],[0,2,6],[0,0,3]])
B = np.array([[1,0,0,0],[0,2,0,0],[0,0,3,0],[0,0,0,4]])
print("Determinant of A=",np.linalg.det(A))
print("Inverse of A=",np.linalg.inv(A))
print("Determinant of B=",np.linalg.det(B))
print("Inverse of B=",np.linalg.inv(B))

Determinant of A= 6.0
Inverse of A= [[ 1.         -2.          2.33333333]
 [ 0.          0.5        -1.        ]
 [ 0.          0.          0.33333333]]
Determinant of B= 23.999999999999993
Inverse of B= [[1.         0.         0.         0.        ]
 [0.         0.5        0.         0.        ]
 [0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0.25      ]]


In [53]:
# Ch Programming Practice
# import numpy as np
# Matrix A and b
A = np.array([[1.0,-1.0,2.0,1.0],[5.0,8.0,6.0,3.0],[4.0,2.0,5.0,3.0],[3.0,2.0,1.0,4.0]])
b = np.array([2.0,10.0,3.0,1.0])
x = np.zeros((4,))

# Forward Elimination
for k in range(0,3):
#     print("k=",k)
    for i in range(k+1,4):
        xmult = A[i][k]/A[k][k] # 2행/1행, 3행/1행, 4행/1행 ...
#         print(xmult)
        for j in range(k,4):
#             print(A[i][j])
            A[i][j] = A[i][j]-xmult*A[k][j]
#         print(A)
        b[i]=b[i]-xmult*b[k]
    
x[3] = b[3]/A[3][3]
# print(x[3], b[3])
# Back substitution
for i in range(2,-1,-1): # 2, 1, 0
    res = b[i]
    for j in range(i+1,4): # 3,4 / 2,3,4 / 1,2,3,4
        res -= (A[i][j]*x[j])
    x[i] = res/A[i][i]
# Result
print("x=",x)
# 원소를 정수로 설정하면 정수연산으로 처리된다. -- 유의할 것

x= [-9.  2.  4.  5.]
