1.5.1 넘파이 가져오기

In [41]:
import numpy as np

1.5.2 넘파이 배열 생성하기

In [42]:
x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [43]:
type(x)

numpy.ndarray

1.5.3 넘파이의 산술 연산

In [44]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x+y

array([3., 6., 9.])

In [45]:
x-y

array([-1., -2., -3.])

In [46]:
x*y

array([ 2.,  8., 18.])

In [47]:
x/y

array([0.5, 0.5, 0.5])

1.5.4 넘파이의 N차원 배열

In [48]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [49]:
A.shape

(2, 2)

In [50]:
A.dtype

dtype('int64')

In [51]:
B = np.array([[3, 0], [0, 6]])
A + B

array([[ 4,  2],
       [ 3, 10]])

In [52]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [53]:
print(A)

[[1 2]
 [3 4]]


In [54]:
A*10

array([[10, 20],
       [30, 40]])

1.5.5 브로드캐스트

In [75]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])

In [76]:
A.shape

(2, 2)

In [77]:
B.shape

(2,)

In [78]:
A * B # 브로드캐스트

array([[10, 40],
       [30, 80]])

In [79]:
print(np.dot(A, B)) # 행렬 연산

[ 50 110]


1.5.6 원소 접근

In [63]:
X = np.array([[51, 55], [14, 19], [0, 4]])
X

array([[51, 55],
       [14, 19],
       [ 0,  4]])

In [64]:
X[0]

array([51, 55])

In [65]:
X[0][1]

55

In [66]:
for row in X:
  print(row)

[51 55]
[14 19]
[0 4]


In [67]:
X = X.flatten()
X

array([51, 55, 14, 19,  0,  4])

In [68]:
X[np.array([0, 2, 4])]

array([51, 14,  0])

In [69]:
X > 15

array([ True,  True, False,  True, False, False])

In [70]:
X[X > 15]

array([51, 55, 19])