1-1: Affine Functions with 1 Feature

Code.1-1-1:Affine Function

In [6]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

# x = tf.constant([[10.],[20.]]) # matrix 형태
# print(x.shape)

x = tf.constant([[10.]]) # input setting (Note: input --> matrix)
print(x)
dense = Dense(units=1, activation='linear') # imp. an affine function
# W, B 값 설정하지 않았기 때문에 dense(x) 통과를 해야 초기화가 진행됨
y_tf = dense(x) # forward propagation + params initialization 
print(y_tf)
W, B = dense.get_weights() # get weight, bias
print(W, B)

y_man = tf.linalg.matmul(x, W) + B # forward propagation(manual)

# print results
print("==== Input/Weight/Bias ====")
print("x: {}\n{}\n".format(x.shape, x.numpy()))
print("W: {}\n{}\n".format(W.shape, W))
print("B: {}\n{}\n".format(B.shape, B))

print("==== Outputs ====")
print("y(Tensorflow): {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y(Manual): {}\n{}\n".format(y_man.shape, y_man.numpy()))

tf.Tensor([[10.]], shape=(1, 1), dtype=float32)
tf.Tensor([[1.7642307]], shape=(1, 1), dtype=float32)
[[0.17642307]] [0.]
==== Input/Weight/Bias ====
x: (1, 1)
[[10.]]

W: (1, 1)
[[0.17642307]]

B: (1,)
[0.]

==== Outputs ====
y(Tensorflow): (1, 1)
[[1.7642307]]

y(Manual): (1, 1)
[[1.7642307]]



Code.1-1-1: Params Initialize

In [10]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant # 내가 원하는 값으로 Initialize

x = tf.constant([[10.]]) # input setting (Note: input --> matrix)

# weight/bias setting
w, b = tf.constant(10.), tf.constant(20.)
w_init, b_init = Constant(w), Constant(b)

# print(w_init, b_init)

# imp. an affine function
dense = Dense(units=1, 
              activation='linear',
              kernel_initializer=w_init,
              bias_initializer=b_init)

y_tf = dense(x)
print(y_tf)
W, B = dense.get_weights()

# print results
print("W: {}\n{}\n".format(W.shape, W))
print("B: {}\n{}\n".format(B.shape, B))

tf.Tensor([[120.]], shape=(1, 1), dtype=float32)
W: (1, 1)
[[10.]]

B: (1,)
[20.]



1-2:Affine Functions wiht n Feature

Code.1-2-1: Affine Functions with n Features

In [13]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

x = tf.random.uniform(shape=(1,10), minval=0, maxval=10)
# print(x.shape, "\n", x)

dense = Dense(units=1)

y_tf = dense(x)

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B

# print results
print("==== Input/Weight/Bias ====")
print("x: {}\n{}\n".format(x.shape, x.numpy()))
print("W: {}\n{}\n".format(W.shape, W))
print("B: {}\n{}\n".format(B.shape, B))

print("==== Outputs ====")
print("y(Tensorflow): {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y(Manual): {}\n{}\n".format(y_man.shape, y_man.numpy()))

==== Input/Weight/Bias ====
x: (1, 10)
[[3.2095087 5.413557  1.9069052 3.197571  6.125516  5.0790844 8.652998
  4.657359  6.7604647 9.5000515]]

W: (10, 1)
[[-0.36706796]
 [ 0.33180732]
 [-0.15193582]
 [ 0.4850871 ]
 [ 0.67162913]
 [ 0.30785888]
 [ 0.657072  ]
 [ 0.143992  ]
 [ 0.6061862 ]
 [ 0.6332262 ]]

B: (1,)
[0.]

==== Outputs ====
y(Tensorflow): (1, 1)
[[24.027287]]

y(Manual): (1, 1)
[[24.027287]]

