1-3: Actication Functions

Code.1-3-1: Activation Layers

In [6]:
import tensorflow as tf

from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

x = tf.random.normal(shape=(1,5)) # input setting

# imp. activation function
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagations(Tensorflow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

# forward propagations(manual)
y_sigmoid_man = 1 / (1+exp(-x))
y_tanh_man = (exp(x)-exp(-x))/(exp(x)+exp(-x))
y_relu_man = maximum(x, 0)

print("x: {}\n{}".format(x.shape, x.numpy()))
print('Sigmoid(Tensorflow: {}\n{}'.format(y_sigmoid_tf.shape,y_sigmoid_tf.numpy()))
print('Sigmoid(Manual: {}\n{}\n'.format(y_sigmoid_man.shape,y_sigmoid_man.numpy()))

print('Tanh(Tensorflow: {}\n{}'.format(y_tanh_tf.shape,y_tanh_tf.numpy()))
print('Tanh(Manual: {}\n{}\n'.format(y_tanh_man.shape,y_tanh_man.numpy()))

print('Relu(Tensorflow: {}\n{}'.format(y_relu_tf.shape,y_relu_tf.numpy()))
print('Relu(Manual: {}\n{}\n'.format(y_relu_man.shape,y_relu_man.numpy()))

x: (1, 5)
[[-2.2622457 -0.5344711  0.6042511 -1.6860691  0.401671 ]]
Sigmoid(Tensorflow: (1, 5)
[[0.09429842 0.3694747  0.64662826 0.15629345 0.599089  ]]
Sigmoid(Manual: (1, 5)
[[0.09429841 0.36947468 0.6466283  0.1562935  0.5990891 ]]

Tanh(Tensorflow: (1, 5)
[[-0.9785521  -0.4887914   0.5400676  -0.9336447   0.38137782]]
Tanh(Manual: (1, 5)
[[-0.97855204 -0.48879132  0.5400677  -0.93364465  0.38137782]]

Relu(Tensorflow: (1, 5)
[[0.        0.        0.6042511 0.        0.401671 ]]
Relu(Manual: (1, 5)
[[0.        0.        0.6042511 0.        0.401671 ]]



Code.1-3-2: Activation in Dense Layer

In [10]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.keras.layers import Dense

x = tf.random.normal(shape=(1,5)) # input setting

# imp. artificial neurons
dense_sigmoid = Dense(units=1, activation='sigmoid')
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

# forward propagations(Tensorflow)
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print("AN with Sigmoid: {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("AN with Tanh: {}\n{}".format(y_tanh.shape, y_tanh.numpy()))
print("AN with Relu: {}\n{}".format(y_relu.shape, y_relu.numpy()))

# forward propagation(manual)
print("\n====\n")

W, b = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x, W) + b
a = 1/(1+exp(-z))
print("Activation value(Tensorflow): {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("Activation value(Manual): {}\n{}".format(a.shape, a.numpy()))

AN with Sigmoid: (1, 1)
[[0.7885866]]
AN with Tanh: (1, 1)
[[-0.5741118]]
AN with Relu: (1, 1)
[[0.]]

====

Activation value(Tensorflow): (1, 1)
[[0.7885866]]
Activation value(Manual): (1, 1)
[[0.7885867]]


1-4: Artificial Neurons

Code.1-4-1: Artificial Neurons

In [13]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

activation = 'sigmoid'
# activation = 'tanh'
# activation = 'relu'

x = tf.random.uniform(shape=(1,10)) # input setting

dense = Dense(units=1, activation=activation) # imp. an affine + activation

y_tf = dense(x)
W, B = dense.get_weights()

# calculate activation value manually
y_man = tf.linalg.matmul(x, W) + B
if activation == 'sigmoid':
  y_man = 1/(1+exp(-y_man))
elif activation == 'tanh':
  y_man = (exp(y_man)-exp(-y_man))/(exp(y_man)+exp(-y_man))
elif activation == 'relu':
  y_man = maximum(y_man, 0)

print('Activation: ', activation)
print("y_tf: {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y_man: {}\n{}\n".format(y_man.shape, y_man.numpy()))

Activation:  sigmoid
y_tf: (1, 1)
[[0.55453104]]

y_man: (1, 1)
[[0.55453104]]



1-5: Minibatches

Code.1-5-1: Shapes of Dense Layers

In [16]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 8, 10 # set input params
x = tf.random.normal(shape=(N, n_feature)) # generate minibatch
# print(x.shape)

dense = Dense(units=1, activation='relu') # imp. an AN
y = dense(x) # forward propagations

W, B = dense.get_weights() # get weigth/bias

# print results
print("Shape of x:", x.shape)
print("Shape of W:", W.shape)
print("Shape of B:", B.shape)

Shape of x: (8, 10)
Shape of W: (10, 1)
Shape of B: (1,)


Code.1-5-2: Output Calculations

In [20]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 8, 10 # set input params
x = tf.random.normal(shape=(N, n_feature)) # generate minibatch

dense = Dense(units=1, activation='sigmoid') # imp. an AN
y_tf = dense(x) # forward propagations(Tensorflow)

W, B = dense.get_weights() # get weight/bias

y_man = tf.linalg.matmul(x, W) + B # forward propagation(Manual)
y_man = 1/(1+tf.math.exp(-y_man))

# print results
print("Output(Tensorflow): \n", y_tf.numpy())
print("Output(Tensorflow): \n", y_man.numpy())
# print(tf.math.equal(y_tf, y_man))

Output(Tensorflow): 
 [[0.40895477]
 [0.21249026]
 [0.2680757 ]
 [0.5947653 ]
 [0.35591614]
 [0.36455953]
 [0.41456658]
 [0.5036428 ]]
Output(Tensorflow): 
 [[0.40895477]
 [0.21249028]
 [0.2680757 ]
 [0.5947653 ]
 [0.35591614]
 [0.36455953]
 [0.41456658]
 [0.5036428 ]]
tf.Tensor(
[[ True]
 [False]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]], shape=(8, 1), dtype=bool)
