2-1: Dense Layers

Code 2-1-1: Shapes of Dense Layers

In [3]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

# N, n_feature = 1, 10  # N = 1 --> mini-batch에서 data sample이 하나
N, n_feature = 8, 10 
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation="sigmoid")
Y = dense(X)

W, B = dense.get_weights()

print("==== Input/Weights/Bias ====")
print("X: ", X.shape)
print("W: ", W.shape)
print("B: ", B.shape)
print("Y: ", Y.shape)

# print(W)

==== Input/Weights/Bias ====
X:  (8, 10)
W:  (10, 3)
B:  (3,)
Y:  (8, 3)


Code 2-1-2: Output Calculations

In [19]:
import numpy as np
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10 
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation="sigmoid")
Y_tf = dense(X)

W, B = dense.get_weights()
print("Y(tensorflow): \n", Y_tf.numpy())

# calculate with matrix multiplication
Z = matmul(X, W) + B
Y_man_matmul = 1/(1 + exp(-Z))
print("Y(with matrix multiplication): \n", Y_man_matmul.numpy())

# calculate with dot products
Y_man_vec = np.zeros(shape=(N, n_neuron))
print(Y_man_vec)
for x_idx in range(N):
  x = X[x_idx]
  for nu_idx in range(n_neuron):
    w, b = W[:,nu_idx], B[nu_idx]
    z = tf.reduce_sum(x * w) + b
    a = 1/(1 + np.exp(-z))
    Y_man_vec[x_idx, nu_idx] = a

print("Y(with dot products): \n", Y_man_vec)

Y(tensorflow): 
 [[0.35408047 0.801633   0.56974244]
 [0.3884276  0.6404854  0.5028319 ]
 [0.31307483 0.6634362  0.6844174 ]
 [0.80961204 0.50824744 0.62347895]]
Y(with matrix multiplication): 
 [[0.35408047 0.80163306 0.5697425 ]
 [0.3884276  0.6404854  0.50283194]
 [0.31307483 0.6634362  0.6844174 ]
 [0.8096121  0.50824744 0.623479  ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Y(with dot products): 
 [[0.35408046 0.801633   0.56974248]
 [0.38842759 0.64048535 0.50283188]
 [0.31307484 0.6634362  0.68441741]
 [0.8096121  0.50824744 0.62347896]]
